[package]
name = "hash-incro"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hashy"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
md5 = "0.7.0"